"""Play Hub source and ingestion-state tables."""

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    Table,
    Text,
    UniqueConstraint,
    Uuid,
)

from lorcana.db.metadata import metadata

playhub_stores = Table(
    "playhub_stores",
    metadata,
    Column("store_id", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("full_address", Text),
    Column("city", Text),
    Column("state_region", Text),
    Column("country", Text),
    Column("latitude", Float),
    Column("longitude", Float),
    Column("email", Text),
    Column("website", Text),
    Column("first_seen", DateTime(timezone=True)),
    Column("last_seen", DateTime(timezone=True)),
    Column("last_synced", DateTime(timezone=True)),
)

playhub_events = Table(
    "playhub_events",
    metadata,
    Column("event_id", BigInteger, primary_key=True, autoincrement=False),
    Column("store_id", Text, ForeignKey("playhub_stores.store_id")),
    Column("name", Text, nullable=False),
    Column("start_datetime", DateTime(timezone=True)),
    Column("end_datetime", DateTime(timezone=True)),
    Column("timezone", Text),
    Column("gameplay_format_id", Text),
    Column("format", Text),
    Column("event_format", Text),
    Column("category", Text),
    Column("display_status", Text),
    Column("event_status", Text),
    Column("lifecycle_status", Text),
    Column("player_count", Integer),
    Column("registered_user_count", Integer),
    Column("capacity", Integer),
    Column("event_is_online", Boolean),
    Column("full_address", Text),
    Column("latitude", Float),
    Column("longitude", Float),
    Column("source_url", Text),
    Column("discovered_at", DateTime(timezone=True)),
    Column("last_synced", DateTime(timezone=True)),
    Index("ix_playhub_events_start_datetime", "start_datetime"),
    Index("ix_playhub_events_gameplay_format_id", "gameplay_format_id"),
    Index("ix_playhub_events_store_id", "store_id"),
)

playhub_phases = Table(
    "playhub_phases",
    metadata,
    Column("phase_id", BigInteger, primary_key=True, autoincrement=False),
    Column("event_id", BigInteger, ForeignKey("playhub_events.event_id"), nullable=False),
    Column("phase_name", Text),
    Column("phase_order", Integer),
    Column("round_type", Text),
    Column("status", Text),
    Index("ix_playhub_phases_event_id", "event_id"),
)

playhub_rounds = Table(
    "playhub_rounds",
    metadata,
    Column("round_id", BigInteger, primary_key=True, autoincrement=False),
    Column("event_id", BigInteger, ForeignKey("playhub_events.event_id"), nullable=False),
    Column("phase_id", BigInteger, ForeignKey("playhub_phases.phase_id")),
    Column("round_number", Integer),
    Column("round_type", Text),
    Column("status", Text),
    Column("pairings_status", Text),
    Column("standings_status", Text),
    Column("final_round_in_event", Boolean, nullable=False, server_default="false"),
    Index("ix_playhub_rounds_event_id", "event_id"),
    Index("ix_playhub_rounds_phase_id", "phase_id"),
)

playhub_players = Table(
    "playhub_players",
    metadata,
    Column("player_id", BigInteger, primary_key=True, autoincrement=False),
    Column("display_name", Text),
    Column("username", Text),
    Column("first_seen", DateTime(timezone=True)),
    Column("last_seen", DateTime(timezone=True)),
    Index("ix_playhub_players_display_name", "display_name"),
    Index("ix_playhub_players_username", "username"),
)

playhub_registrations = Table(
    "playhub_registrations",
    metadata,
    Column("registration_id", BigInteger, primary_key=True, autoincrement=False),
    Column("event_id", BigInteger, ForeignKey("playhub_events.event_id"), nullable=False),
    Column("player_id", BigInteger, ForeignKey("playhub_players.player_id"), nullable=False),
    Column("display_name_at_event", Text),
    Column("registration_status", Text),
    Column("matches_won", Integer),
    Column("matches_lost", Integer),
    Column("matches_drawn", Integer),
    Column("match_points", Integer),
    Column("placement", Integer),
    Column("registered_at", DateTime(timezone=True)),
    Column("last_synced", DateTime(timezone=True)),
    UniqueConstraint("event_id", "player_id", name="uq_playhub_registrations_event_player"),
    Index("ix_playhub_registrations_event_id", "event_id"),
    Index("ix_playhub_registrations_player_id", "player_id"),
)

playhub_matches = Table(
    "playhub_matches",
    metadata,
    Column("match_id", BigInteger, primary_key=True, autoincrement=False),
    Column("event_id", BigInteger, ForeignKey("playhub_events.event_id"), nullable=False),
    Column("round_id", BigInteger, ForeignKey("playhub_rounds.round_id"), nullable=False),
    Column("player1_id", BigInteger, ForeignKey("playhub_players.player_id")),
    Column("player2_id", BigInteger, ForeignKey("playhub_players.player_id")),
    Column("participant_count", Integer),
    Column("player1_score", Integer),
    Column("player2_score", Integer),
    Column("winner_id", BigInteger, ForeignKey("playhub_players.player_id")),
    Column("status", Text),
    Column("table_number", Integer),
    Column("is_draw", Boolean, nullable=False, server_default="false"),
    Column("is_intentional_draw", Boolean, nullable=False, server_default="false"),
    Column("is_unintentional_draw", Boolean, nullable=False, server_default="false"),
    Column("is_bye", Boolean, nullable=False, server_default="false"),
    Column("is_loss", Boolean, nullable=False, server_default="false"),
    Column("is_ghost_match", Boolean, nullable=False, server_default="false"),
    Column("is_feature_match", Boolean, nullable=False, server_default="false"),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Index("ix_playhub_matches_event_id", "event_id"),
    Index("ix_playhub_matches_round_id", "round_id"),
    Index("ix_playhub_matches_player1_id", "player1_id"),
    Index("ix_playhub_matches_player2_id", "player2_id"),
)

playhub_discovery_runs = Table(
    "playhub_discovery_runs",
    metadata,
    Column("discovery_run_id", Uuid, primary_key=True),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True)),
    Column("start_datetime", DateTime(timezone=True), nullable=False),
    Column("end_datetime", DateTime(timezone=True), nullable=False),
    Column("events_received", Integer, nullable=False, server_default="0"),
    Column("unique_events", Integer, nullable=False, server_default="0"),
    Column("duplicate_rows", Integer, nullable=False, server_default="0"),
    Column("status", Text, nullable=False),
    Column("error_category", Text),
    Column("error_summary", Text),
)

playhub_event_sync_state = Table(
    "playhub_event_sync_state",
    metadata,
    Column("event_id", BigInteger, ForeignKey("playhub_events.event_id"), primary_key=True),
    Column("state", Text, nullable=False),
    Column("last_attempt_at", DateTime(timezone=True)),
    Column("last_success_at", DateTime(timezone=True)),
    Column("last_error_category", Text),
    Column("last_error_summary", Text),
    Column("source_revision", Text),
    CheckConstraint(
        "state IN ('discovered','pending','syncing','complete','partial','no_results','failed')",
        name="playhub_event_sync_state_state",
    ),
    Index("ix_playhub_event_sync_state_state", "state"),
)

playhub_import_attempts = Table(
    "playhub_import_attempts",
    metadata,
    Column("import_attempt_id", Uuid, primary_key=True),
    Column("event_id", BigInteger, ForeignKey("playhub_events.event_id"), nullable=False),
    Column("job_id", Uuid),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True)),
    Column("status", Text, nullable=False),
    Column("rounds_expected", Integer),
    Column("rounds_imported", Integer),
    Column("registrations_found", Integer),
    Column("matches_found", Integer),
    Column("players_found", Integer),
    Column("error_category", Text),
    Column("error_summary", Text),
    CheckConstraint(
        "status IN ('running','complete','partial','no_results','failed')",
        name="playhub_import_attempts_status",
    ),
    Index("ix_playhub_import_attempts_event_id", "event_id"),
    Index("ix_playhub_import_attempts_started_at", "started_at"),
)
